language: python
python:
    - "3.6"
sudo: false
services:
    - mysql
before_script:
    - mysql -e 'CREATE DATABASE mrtallyman_test;'
environment:
    MYSQL_USER: travis
install: pip install -q -r requirements-testing.txt
script: pytest
cache:
    directories:
        - .cache
        - $HOME/.cache/pip
    timeout: 3600
