AFFIRMATIONS = [
    "A-1!",
    "A-okay!",
    "Absolutely!",
    "Accomplishment achieved!",
    "Acknowledged!",
    "Admirable!",
    "Affirmative!",
    "Alright!",
    "Aww yeah!",
    "Best!",
    "Bravo!",
    "Brilliantly executed!",
    "By all means!",
    "Capital work!",
    "Capital!",
    "Certainly!",
    "Champion!",
    "Choice!",
    "Civilized.",
    "Commendable!",
    "Completed.",
    "Copy!",
    "Decent.",
    "Dignified.",
    "Done.",
    "Effective immediately!",
    "Excellent!",
    "Exceptional!",
    "Executed!",
    "Exquisite!",
    "Fabulous!",
    "Fantastic!",
    "Fitting!",
    "Five-star!",
    "Flawless!",
    "Formidable!",
    "Great job!",
    "Immaculate!",
    "Impeccable!",
    "Impressive!",
    "Kudos!",
    "Magnificent!",
    "Marvelous!",
    "Masterful!",
    "Matchless!",
    "Nailed it!",
    "Nice.",
    "Nonpareil!",
    "OK!",
    "Okay.",
    "Okey-dokey!",
    "On the mark!",
    "Outstanding!",
    "Perfect!",
    "Perfect.",
    "Perfection!",
    "Perfecto!",
    "Phenomenal!",
    "Polite.",
    "Praiseworthy!",
    "Premium!",
    "Remarkable!",
    "Respectable.",
    "Right on!",
    "Seemly.",
    "Sexy!",
    "Sheer perfection!",
    "Solid!",
    "Sound!",
    "Splendid!",
    "Splendiferous!",
    "Spot on!",
    "Spot-on!",
    "Spotless!",
    "Stellar!",
    "Sterling!",
    "Straight-up!",
    "Success!",
    "Super!",
    "Superb!",
    "Superb.",
    "Superior!",
    "Supreme!",
    "Terrific!",
    "The best!",
    "Very suitable.",
    "Well done!",
]

BANANA_URLS = [
        'https://www.youtube.com/watch?v=sFukyIIM1XI',
        'https://www.youtube.com/shorts/eQqdkEU_bng',
        'https://www.youtube.com/shorts/FOEo3waXr6s',
        'https://www.youtube.com/shorts/itOGN_a-vBM',
        'https://www.youtube.com/shorts/8GqiGGI3TyM',
        ]
DAYO_URLS = [
        'https://www.youtube.com/watch?v=AQXVHITd1N4',
        'https://www.youtube.com/watch?v=H5dpBWlRANE',
        'https://www.youtube.com/watch?v=hpuwILAUgoc',
        'https://www.youtube.com/watch?v=hHnxOJlvdwU',
        ]
